name: suits
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  image_picker: ^1.0.7
  intl: ^0.18.1
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.10+1
  pin_code_fields: ^8.0.1
  easy_localization: ^3.0.4
  flutter_slidable: ^3.1.0
  dotted_line: ^3.2.2
  dotted_border: ^2.1.0
  lottie: ^3.1.0
  shared_preferences: ^2.2.2
  animate_do: ^3.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: WaterFall
      fonts:
        - asset: assets/fonts/waterfall.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/inter.ttf
    - family: Arial
      fonts:
        - asset: assets/fonts/arial.ttf

  assets:
    - assets/translations/
    - assets/fonts/
    - assets/images/
    - assets/svg/
    - assets/lottie/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

